<a href="https://colab.research.google.com/github/skhan226/Hyperparameter-Tuning-of-Machine-Learning-Model-in-Python/blob/main/hyperparameter_tuning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tuning Hyperparameters of Machine Learning Model**

Shoeb Ahmed Khan

In this Jupyter notebook, we will be tuning hyperparameters of a classification model built by random forest algorithm using scikit-learn package in Python.

## **1. Importing the dataset**

In [ ]:
from google.colab import drive 
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [ ]:
! ls

complied_data  gdrive  loan_default.csv  loan_default.csv.1  sample_data


In [ ]:
! ls -l

total 140
drwxr-xr-x 2 root root  4096 Dec 27 21:05 complied_data
drwx------ 6 root root  4096 Dec 27 21:28 gdrive
-rw-r--r-- 1 root root 62445 Aug 21  2018 loan_default.csv
-rw-r--r-- 1 root root 62445 Aug 21  2018 loan_default.csv.1
drwxr-xr-x 1 root root  4096 Dec  3 14:33 sample_data


In [ ]:
! mkdir complied_data

mkdir: cannot create directory ‘complied_data’: File exists


In [ ]:
! ls

complied_data  gdrive  loan_default.csv  loan_default.csv.1  sample_data


In [ ]:
! wget https://bigblue.depaul.edu/jlee141/econdata/eco520/loan_default.csv

--2021-12-27 21:28:54--  https://bigblue.depaul.edu/jlee141/econdata/eco520/loan_default.csv
Resolving bigblue.depaul.edu (bigblue.depaul.edu)... 216.220.181.67
Connecting to bigblue.depaul.edu (bigblue.depaul.edu)|216.220.181.67|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62445 (61K) [text/csv]
Saving to: ‘loan_default.csv.2’

loan_default.csv.2  100%[===================>]  60.98K  --.-KB/s    in 0.1s    

2021-12-27 21:28:55 (603 KB/s) - ‘loan_default.csv.2’ saved [62445/62445]



In [ ]:
import pandas as pd
loan = pd.read_csv("loan_default.csv")

In [ ]:
loan=loan.rename(columns={'Marital_status ':'Rstatus'})

In [ ]:
loan

Default  Checking_amount  Term  ...  Emp_duration   Age No_of_credit_acc
0          0              988    15  ...             12   38                1
1          0              458    15  ...             25   36                1
2          0              158    14  ...             43   34                1
3          1              300    25  ...              0   29                1
4          1               63    24  ...              4   30                1
..       ...              ...   ...  ...            ...  ...              ...
995        1               17    21  ...            118   28                5
996        0              590    18  ...            108   29                5
997        0              343    16  ...             99   31                4
998        0              709    16  ...            113   28                6
999        0              991    15  ...             95   33                8

[1000 rows x 16 columns]

### **1.2. Let's examine the data dimension**

We can see that there are 1000 rows (samples) and 16 columns (features) in the **loan** dataset

In [ ]:
loan.shape

(1000, 16)

### **1.3. Preprocessing the data **

1.Finding the unique variables in **Gender** , **Emp_status** and **Rstatus**, assigning arbitrary code to each unique value.
2.Shuffling the dataset
3.Dropping the Default value and from the data set and creating a differnt dataset with just the Default values

In [ ]:
loan["Gender"].unique()

array([0, 1], dtype=int8)

0 = Female & 1 = male

In [ ]:
loan.Gender=loan["Gender"].astype("category").cat.codes

In [ ]:
loan["Emp_status"].unique()

array([0, 1], dtype=int8)

Employed = 0 & Unemployed= 1

In [ ]:
loan.Emp_status=loan["Emp_status"].astype("category").cat.codes

In [ ]:
loan['Rstatus'].unique()

array(['Single', 'Married'], dtype=object)

Married= 0 & single= 1

In [ ]:
loan.Rstatus=loan["Rstatus"].astype("category").cat.codes

In [ ]:
loan['Default']=pd.factorize(loan.Default)[0]

In [ ]:
loan

Default  Checking_amount  Term  ...  Emp_duration   Age  No_of_credit_acc
0          0              988    15  ...             12   38                 1
1          0              458    15  ...             25   36                 1
2          0              158    14  ...             43   34                 1
3          1              300    25  ...              0   29                 1
4          1               63    24  ...              4   30                 1
..       ...              ...   ...  ...            ...  ...               ...
995        1               17    21  ...            118   28                 5
996        0              590    18  ...            108   29                 5
997        0              343    16  ...             99   31                 4
998        0              709    16  ...            113   28                 6
999        0              991    15  ...             95   33                 8

[1000 rows x 16 columns]

In [ ]:
import sklearn
from sklearn import preprocessing
loan = sklearn.utils.shuffle(loan)


In [ ]:
X=loan.drop("Default",axis=1).values
Y=loan['Default'].values

In [ ]:
X

array([[437,  18, 853, ...,  34,  36,   1],
       [745,  14, 812, ...,  46,  38,   1],
       [190,  13, 821, ...,  93,  31,   1],
       ...,
       [301,  15, 815, ...,   4,  35,   3],
       [626,  17, 819, ...,  24,  34,   2],
       [363,  17, 783, ...,  78,  36,   2]])

In [ ]:
Y

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,

In [ ]:
X.shape, Y.shape

((1000, 15), (1000,))

## **2. Data split (80/20 ratio)**

### **2.1. Data split**

A ratio of 80/20 is used for data splitting such that 80% goes to the training subset and 20% to the testing subset.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.2)

### **2.2. Let's examine the data dimension**

Here we see that the **training set** has 800 rows and 115 columns while there are 800 rows and 1 column for the **Y** variable.

In [ ]:
X_train.shape, Y_train.shape

((800, 15), (800,))

The **testing set** has 200 rows and 15 columns for the **X** variable while there are 200 rows and 1 column for the **Y** variable.

In [ ]:
X_test.shape, Y_test.shape

((200, 15), (200,))

# **3. Building a simple machine learning model using Random Forest**

In the following blocks of codes, we will first start with building a random forest model. Finally, we will explore how to tune the hyperparameters (e.g. **n_estimators** and **max_features**) of the random forest algorithm. 

We first start by importing the necessary libraries and assigning the random forest classifier to the **rf** variable.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(max_features=5, n_estimators=100)

Now, we will be applying the random forest classifier to build a classification model using the **rf.fit()** function on the training data (e.g. **X_train** and **Y_train**).

In [ ]:
rf.fit(X_train, Y_train)

RandomForestClassifier(max_features=5)

The **rf.score()** function will be used to calculate the accuracy score of the RF model in predicting the *test data* (**X_test**).

In [ ]:
rf.score(X_test, Y_test)

0.93

The following 2 code cells also calculate the accuracy score of the RF model in predicting the test data (X_test) but performs it in 2 steps using **rf.predict()** and **accuracy_score()** functions.

In [ ]:
Y_pred =rf.predict(X_test)

In [ ]:
accuracy_score(Y_pred, Y_test)

0.93

The advantage of using this latter approach is that you have access to the predicted data values.

In [ ]:
Y_pred, Y_test

(array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        1, 0]),
 array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0,

# **4. Hyperparameter Tuning**

Now we will be performing the tuning of hyperparameters of Random forest model. The hyperparameters that we will tune includes **max_features** and the **n_estimators**.

Note: Some codes modified from [scikit-learn](http://scikit-learn.org/stable/auto_examples/svm/plot_rbf_parameters.html)

Firstly, we will import the necessary modules.

The **GridSearchCV()** function from scikit-learn will be used to perform the hyperparameter tuning. Particularly, **GridSearchCV()** function can perform the typical functions of a classifier such as ***fit***, ***score*** and ***predict*** as well as ***predict_proba***, ***decision_function***, ***transform*** and ***inverse_transform***.

Secondly, we define variables that are necessary input to the GridSearchCV() function.


In [ ]:
from sklearn.model_selection import GridSearchCV
import numpy as np

max_features_range = np.arange(1,6,1)
n_estimators_range = np.arange(10,210,10)
param_grid = dict(max_features=max_features_range, n_estimators=n_estimators_range)

rf = RandomForestClassifier()

grid = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)



In [ ]:
grid.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_features': array([1, 2, 3, 4, 5]),
                         'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])})

In [ ]:
print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))

The best parameters are {'max_features': 2, 'n_estimators': 140} with a score of 0.95


# **5. Dataframe of Grid search parameters and their Accuracy scores**

Finally, we will be exporting the grid search parameters and their resulting accuracy scores into a dataframe.

In [ ]:
import pandas as pd

grid_results = pd.concat([pd.DataFrame(grid.cv_results_["params"]),pd.DataFrame(grid.cv_results_["mean_test_score"], columns=["Accuracy"])],axis=1)
grid_results

max_features  n_estimators  Accuracy
0              1            10   0.89000
1              1            20   0.92500
2              1            30   0.93125
3              1            40   0.93500
4              1            50   0.93125
..           ...           ...       ...
95             5           160   0.93750
96             5           170   0.94250
97             5           180   0.94375
98             5           190   0.94375
99             5           200   0.94250

[100 rows x 3 columns]

# **6. Preparing data for making contour plots**

Prior to making contour plots, we will have to reshape the data into a compatible format that will be recognized by the contour plot functions.

Firstly, we will be using Pandas' **groupby()** function to segment the data into groups based on the 2 hyperparameters: **max_features** and **n_estimators**.

In [ ]:
grid_contour = grid_results.groupby(['max_features','n_estimators']).mean()
grid_contour

Accuracy
max_features n_estimators          
1            10             0.89000
             20             0.92500
             30             0.93125
             40             0.93500
             50             0.93125
...                             ...
5            160            0.93750
             170            0.94250
             180            0.94375
             190            0.94375
             200            0.94250

[100 rows x 1 columns]

## **Pivoting the data**

Data is reshaped by pivoting the data into an m by n matrix where rows and columns correspond to the **max_features** and **n_estimators**, respectively.

In [ ]:
grid_reset = grid_contour.reset_index()
grid_reset.columns = ['max_features', 'n_estimators', 'Accuracy']
grid_pivot = grid_reset.pivot('max_features', 'n_estimators')
grid_pivot

Accuracy                   ...                           
n_estimators      10      20       30   ...      180      190      200
max_features                            ...                           
1             0.89000  0.9250  0.93125  ...  0.93750  0.93875  0.93750
2             0.92500  0.9300  0.93500  ...  0.94125  0.94875  0.94500
3             0.93125  0.9300  0.93875  ...  0.94625  0.94500  0.94250
4             0.92875  0.9325  0.95000  ...  0.94375  0.94500  0.94125
5             0.92500  0.9350  0.94625  ...  0.94375  0.94375  0.94250

[5 rows x 20 columns]

Finally, we assign the pivoted data into the respective ***x***, ***y*** and ***z*** variables.

In [ ]:
x = grid_pivot.columns.levels[1].values
y = grid_pivot.index.values
z = grid_pivot.values

# **2D Contour Plot**

Now, comes the fun part, we will be visualizing the landscape of the 2 hyperparameters that we are tuning and their influence on the accuracy score.

In [ ]:
import plotly.graph_objects as go

# X and Y axes labels
layout = go.Layout(
            xaxis=go.layout.XAxis(
              title=go.layout.xaxis.Title(
              text='n_estimators')
             ),
             yaxis=go.layout.YAxis(
              title=go.layout.yaxis.Title(
              text='max_features') 
            ) )

fig = go.Figure(data = [go.Contour(z=z, x=x, y=y)], layout=layout )

fig.update_layout(title='Hyperparameter tuning', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()

# **3D Surface Plot**

Let's add an extra dimension to the plot and we now have a 3D surface plot. The cool thing about this plot is that you can rotate the graph.

In [ ]:
import plotly.graph_objects as go


fig = go.Figure(data= [go.Surface(z=z, y=y, x=x)], layout=layout )
fig.update_layout(title='Hyperparameter tuning',
                  scene = dict(
                    xaxis_title='n_estimators',
                    yaxis_title='max_features',
                    zaxis_title='Accuracy'),
                  autosize=False,
                  width=800, height=800,
                  margin=dict(l=65, r=50, b=65, t=90))
fig.show()